export default {
    ts: "TypeScript",
    js: "JavaScript",
    python: "Python",
    sqlite: "SQLite",
    mongo: "MongoDB",
    postgreSql: "PostgreSQL",
    html: "HTML",
    css: "CSS",
    sass: "SASS",
    scss: "SCSS",
    less: "Less",
    stylus: "Stylus",
    ejs: "EJS",
    jinja: "Jinja2",
    node: "Node.js",
    javascript: "JavaScript",
    vscode: "VSCode",
    nvim: "NeoVim",
    figma: "Figma",
    git: "Git & GitHub",
    xfce: "XFCE",
    react: "React",
    discordJs: "Discord.js",
    flask: "Flask",
    quart: "Quart",
    express: "Express",
    symfony: "Symfony",
    rtk: "RTK",
    zod: "Zod",
    webpack: "WebPack",
    pug: "Pug",
    gulp: "Gulp",
    next: "Next",
    deno: "Deno",
    pixijs: "PixiJS",
    preact: "Preact",
    // Networking & infrastructure
    cisco: "Cisco",
    huawei: "Huawei",
    xdsl: "xDSL",
    ethTrunk: "Eth-Trunk",
    layer3: "Layer 3 switching",
    routing: "Routing (RIP/Static)",
    networkDesign: "Network design",
    acl: "ACL",
    qos: "QoS",
    dhcp: "DHCP",
    dns: "DNS",
    fiber: "Fibre Optic",
    gns3: "GNS3",
    ensp: "eNSP",
    packetTracer: "Packet Tracer",
    eveNg: "EVE-NG",
    // Security & pentesting
    metasploit: "Metasploit",
    nessus: "Nessus",
    openvas: "OpenVAS",
    nmap: "Nmap",
    burp: "Burp Suite",
    kali: "Kali Linux",
    php: "PHP",
    java: "Java",
    twig: "Twig",
    mysql: "MySQL",
    chartjs: "Chart.js",
    // SIEM / Monitoring
    siem: "SIEM",
    elasticsearch: "Elasticsearch",
    logstash: "Logstash",
    kibana: "Kibana",
    wazuh: "Wazuh",
    filebeat: "Filebeat",
    winlogbeat: "Winlogbeat",
    // Fortinet and security appliances
    fortinet: "Fortinet",
    forti: "FortiGate",
    // Networking/security
    openvpn: "OpenVPN",
    ipsec: "IPsec",
    ips: "IPS",
    ids: "IDS",
    // Monitoring & tools
    wireshark: "Wireshark",
    tcpdump: "TCPDump",
    netstat: "Netstat",
    htop: "htop",
    snmp: "SNMP",
    syslog: "Syslog",
    ssh: "SSH",
    // Automation & virtualization
    ansible: "Ansible",
    bash: "Bash",
    powershell: "PowerShell",
    docker: "Docker",
    vmware: "VMware",
    esxi: "ESXi",
    virtualbox: "VirtualBox",
    // Low-level
    assembly: "Assembly",
}